#!/bin/sh

pattern='^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: .+$'

if ! grep -qE "$pattern" "$1"; then
  echo "Error: Commit message does not follow Conventional Commits format." >&2
  echo "Example: feat(lang): add new translations" >&2
  exit 1
fi

