# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_symbol = "[❮](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

format = "$all${custom.git_email}"

### Custom comands
[custom.git_email]
command = "git config user.email"
when = "git rev-parse --git-dir 2> /dev/null"
format = "by [$output]($style) "
style = "bright-yellow bold"
