
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
format = """
(git user: $custom\n)\
$directory\
$direnv\
$git_branch\
$git_status\
$fill\
$lua\
$python\
$golang\
$nodejs\
$gcloud\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[➜](bold green)"
vimcmd_symbol = "[❮](bold green)"  # vi-mode symbol

[directory]
truncate_to_repo = false
truncation_symbol = ".../"
truncation_length = 6
style = "bold blue"

[direnv]
disabled = false
format = "[.envrc $loaded/$allowed]($style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold yellow"

[fill]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[golang]
symbol = " "
format = '[$symbol($version )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[gcloud]
symbol = "󱇶 "
format = '[$symbol$active(\($region\))]($style) '

### Custom comands
[custom.git_email]
command = "git config user.email"
when = "git rev-parse --git-dir 2> /dev/null"
format = "[$output]($style)"
style = "green bold"
