[notebook]
dir = "~/notes"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[extra]
author = "Ramon Vermeulen"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y'}}/{{format-date now '%m'}}/{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.monthly]
paths = ["monthly"]

[group.monthly.note]
filename = "{{format-date now '%Y'}}/{{format-date now '%m'}}/monthly_notes"
extension = "md"
template = "monthly.md"

[format.markdown]
hashtags = true
colon-tags = true

[tool]
editor = "nvim"
shell = "/bin/zsh"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
monthly = 'zk new --no-input "$ZK_NOTEBOOK_DIR/monthly"'
ls = "zk edit --interactive"


[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
