#!/usr/bin/env bash

# Carbonfox Color Palette
black="0xff161616"
blue="0xff78A9FF"
blue1="0xff0f0f0f" # darker background
blue1_semitransparent="0xaa0f0f0f"
cyan="0xff33B1FF"
green="0xff25be6a"
magenta="0xffBE95FF"
orange="0xff3DDBD9" # note: carbonfox uses teal for orange
purple="0xffBE95FF" # using magenta for purple
red="0xffEE5396"
transparent="0x00000000"
white="0xffdfdfe0"
yellow="0xff08BDBA" # teal/yellow

# Defaults
BAR_BLUR_RADIUS=30
BAR_COLOR="$transparent"
BAR_CORNER_RADIUS=12
BAR_HEIGHT=24
BAR_MARGIN=6
BAR_PADDING=0
BAR_POSITION="top"
BAR_Y_OFFSET=6

BACKGROUND_BORDER_COLOR="$red"
BACKGROUND_BORDER_WIDTH=2
BACKGROUND_COLOR="$blue1_semitransparent"
BACKGROUND_CORNER_RADIUS=4
BACKGROUND_HEIGHT=24

BRACKET_BACKGROUND_BORDER_COLOR="$blue"
BRACKET_BACKGROUND_BORDER_WIDTH=0
BRACKET_BACKGROUND_COLOR="$blue1_semitransparent"
BRACKET_BACKGROUND_CORNER_RADIUS=12

ICON_BASE_FONT="SF Pro"
ICON_FONT="$ICON_BASE_FONT:Bold:14.0"

LABEL_ALIGN="center"
LABEL_BASE_FONT="JetBrainsMono Nerd Font"
LABEL_COLOR="$blue"
LABEL_FONT="$LABEL_BASE_FONT:Regular:14.0"
LABEL_HIGHLIGHT_COLOR="$red"
LABEL_HIGHLIGHT_FONT="$LABEL_BASE_FONT:ExtraBold:14.0"
LABEL_PADDING=6
LABEL_Y_OFFSET=1
